<?php

namespace Database\Seeders;

use App\Models\Admin\GameList;
use Illuminate\Database\Seeder;

class CQ9GameListTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = [
            [
                "code" => "1",
                "name" => "FruitKing",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/1.png",
            ],
            [
                "code" => "3",
                "name" => "VampireKiss",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/3.png",
            ],
            [
                "code" => "15",
                "name" => "GuGuGu",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/15.png",
            ],
            [
                "code" => "16",
                "name" => "Super5",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/16.png",
            ],
            [
                "code" => "20",
                "name" => "888",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/20.png",
            ],
            [
                "code" => "22",
                "name" => "MonkeyOfficeLegend",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/22.png",
            ],
            [
                "code" => "42",
                "name" => "SherlockHolmes",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/42.png",
            ],
            [
                "code" => "AS18",
                "name" => "Wild Fudge",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AS18.png",
            ],
            [
                "code" => "23",
                "name" => "YuanBao",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/23.png",
            ],
            [
                "code" => "24",
                "name" => "RaveJump2",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/24.png",
            ],
            [
                "code" => "33",
                "name" => "FireChibi",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/33.png",
            ],
            [
                "code" => "35",
                "name" => "CrazyNuozha",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/35.png",
            ],
            [
                "code" => "49",
                "name" => "LonelyPlanet",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/49.png",
            ],
            [
                "code" => "52",
                "name" => "JumpHigh",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/52.png",
            ],
            [
                "code" => "58",
                "name" => "GuGuGu2",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/58.png",
            ],
            [
                "code" => "201",
                "name" => "MuayThai",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/201.png",
            ],
            [
                "code" => "105",
                "name" => "JumpingMobile",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/105.png",
            ],
            [
                "code" => "AS02",
                "name" => "Cirque de fous",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AS02.png",
            ],
            [
                "code" => "AS10",
                "name" => "Lucky 3",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AS10.png",
            ],
            [
                "code" => "4",
                "name" => "WildTarzan",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/4.png",
            ],
            [
                "code" => "19",
                "name" => "HotSpin",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/19.png",
            ],
            [
                "code" => "21",
                "name" => "BigWolf",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/21.png",
            ],
            [
                "code" => "32",
                "name" => "DetectiveDee",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/32.png",
            ],
            [
                "code" => "34",
                "name" => "GophersWar",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/34.png",
            ],
            [
                "code" => "44",
                "name" => "FruitKingII",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/44.png",
            ],
            [
                "code" => "51",
                "name" => "EcstaticCircus",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/51.png",
            ],
            [
                "code" => "72",
                "name" => "HappyRichYear",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/72.png",
            ],
            [
                "code" => "AS03",
                "name" => "Dragon Hunters",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AS03.png",
            ],
            [
                "code" => "AS04",
                "name" => "Fortune Spirits",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AS04.png",
            ],
            [
                "code" => "2",
                "name" => "GodOfChess",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/2.png",
            ],
            [
                "code" => "5",
                "name" => "Mr.Rich",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/5.png",
            ],
            [
                "code" => "7",
                "name" => "RaveJump",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/7.png",
            ],
            [
                "code" => "12",
                "name" => "TreasureHouse",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/12.png",
            ],
            [
                "code" => "29",
                "name" => "WaterWorld",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/29.png",
            ],
            [
                "code" => "31",
                "name" => "GodofWar",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/31.png",
            ],
            [
                "code" => "69",
                "name" => "FaCaiShen",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/69.png",
            ],
            [
                "code" => "60",
                "name" => "JungleParty",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/60.png",
            ],
            [
                "code" => "AS09",
                "name" => "Hollywood Pets",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AS09.png",
            ],
            [
                "code" => "8",
                "name" => "SoSweet",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/8.png",
            ],
            [
                "code" => "10",
                "name" => "LuckyBats",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/10.png",
            ],
            [
                "code" => "202",
                "name" => "OrientalBeauty",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/202.png",
            ],
            [
                "code" => "9",
                "name" => "ZhongKui",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/9.png",
            ],
            [
                "code" => "17",
                "name" => "GreatLion",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/17.png",
            ],
            [
                "code" => "39",
                "name" => "Apsaras",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/39.png",
            ],
            [
                "code" => "47",
                "name" => "Pharaoh's Gold",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/47.png",
            ],
            [
                "code" => "70",
                "name" => "WanbaoDino",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/70.png",
            ],
            [
                "code" => "AS01",
                "name" => "Boots of Luck",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AS01.png"
            ],
            [
                "code" => "AS19",
                "name" => "Xmas Tales",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AS19.png"
            ],
            [
                "code" => "38",
                "name" => "AllWilds",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/38.png",
            ],
            [
                "code" => "54",
                "name" => "FunnyAlpaca",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/54.png",
            ],
            [
                "code" => "99",
                "name" => "JumpHigher",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/99.png",
            ],
            [
                "code" => "89",
                "name" => "Thor",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/89.png",
            ],
            [
                "code" => "AS08",
                "name" => "Golden Mayan",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AS08.png",
            ],
            [
                "code" => "AS17",
                "name" => "Treasure of Seti",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AS17.png"
            ],
            [
                "code" => "13",
                "name" => "SakuraLegend",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/13.png",
            ],
            [
                "code" => "26",
                "name" => "777",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/26.png",
            ],
            [
                "code" => "27",
                "name" => "MagicWorld",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/27.png",
            ],
            [
                "code" => "36",
                "name" => "PubTycoon",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/36.png",
            ],
            [
                "code" => "46",
                "name" => "WolfMoon",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/46.png",
            ],
            [
                "code" => "50",
                "name" => "GoodFortune",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/50.png",
            ],
            [
                "code" => "57",
                "name" => "TheBeastWar",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/57.png",
            ],
            [
                "code" => "66",
                "name" => "Fire777",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/66.png",
            ],
            [
                "code" => "AS20",
                "name" => "Queen Of Dead",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AS20.png",
            ],
            [
                "code" => "113",
                "name" => "FlyingCaiShen",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/113.png",
            ],
            [
                "code" => "108",
                "name" => "JumpHigherMobile",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/108.png",
            ],
            [
                "code" => "121",
                "name" => "RaveJump2M",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/121.png",
            ],
            [
                "code" => "128",
                "name" => "WheelMoney",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/128.png",
            ],
            [
                "code" => "203",
                "name" => "RaveHigh",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/203.png",
            ],
            [
                "code" => "143",
                "name" => "FaCaiFuWa",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/143.png",
            ],
            [
                "code" => "102",
                "name" => "FruityCarnival",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/102.png",
            ],
            [
                "code" => "124",
                "name" => "InvincibleElephant",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/124.png",
            ],
            [
                "code" => "125",
                "name" => "ZeusM",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/125.png",
            ],
            [
                "code" => "76",
                "name" => "WonWonWon",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/76.png",
            ],
            [
                "code" => "77",
                "name" => "RedPhoenix",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/77.png",
            ],
            [
                "code" => "1074",
                "name" => "TreasureBowlJP",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/1074.png",
            ],
            [
                "code" => "92",
                "name" => "WorldCupRussia2018",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/92.png",
            ],
            [
                "code" => "139",
                "name" => "FireChibiM",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/139.png",
            ],
            [
                "code" => "AS33",
                "name" => "Pig Of Luck",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AS33.png",
            ],
            [
                "code" => "221",
                "name" => "Detective Dee 2",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/221.png",
            ],
            [
                "code" => "131",
                "name" => "FaCaiShenM",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/131.png",
            ],
            [
                "code" => "132",
                "name" => "Meow",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/132.png",
            ],
            [
                "code" => "68",
                "name" => "Wukong&Peaches",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/68.png",
            ],
            [
                "code" => "83",
                "name" => "FireQueen",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/83.png",
            ],
            [
                "code" => "95",
                "name" => "FootballBoots",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/95.png",
            ],
            [
                "code" => "112",
                "name" => "PyramidRaider",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/112.png",
            ],
            [
                "code" => "122",
                "name" => "ZumaWild",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/122.png",
            ],
            [
                "code" => "137",
                "name" => "DiscoNightM",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/137.png",
            ],
            [
                "code" => "80",
                "name" => "Poseidon",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/80.png",
            ],
            [
                "code" => "81",
                "name" => "TreasureIsland",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/81.png",
            ],
            [
                "code" => "1010",
                "name" => "LuckyBatsJP",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/1010.png",
            ],
            [
                "code" => "1067",
                "name" => "GoldenEggsJP",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/1067.png",
            ],
            [
                "code" => "96",
                "name" => "FootballBaby",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/96.png",
            ],
            [
                "code" => "59",
                "name" => "SummerMood",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/59.png",
            ],
            [
                "code" => "141",
                "name" => "Xmas",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/141.png",
            ],
            [
                "code" => "142",
                "name" => "Hephaestus",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/142.png",
            ],
            [
                "code" => "104",
                "name" => "ChickyParmParm",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/104.png",
            ],
            [
                "code" => "116",
                "name" => "Wonderland",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/116.png",
            ],
            [
                "code" => "133",
                "name" => "GoodFortuneM",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/133.png",
            ],
            [
                "code" => "135",
                "name" => "GuGuGuM",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/135.png",
            ],
            [
                "code" => "136",
                "name" => "RunningAnimals",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/136.png",
            ],
            [
                "code" => "86",
                "name" => "RunningToro",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/86.png",
            ],
            [
                "code" => "144",
                "name" => "DiamondTreasure",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/144.png",
            ],
            [
                "code" => "115",
                "name" => "SnowQueen",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/115.png",
            ],
            [
                "code" => "74",
                "name" => "TreasureBowl",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/74.png",
            ],
            [
                "code" => "78",
                "name" => "Apollo",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/78.png",
            ],
            [
                "code" => "55",
                "name" => "DragonHeart",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/55.png",
            ],
            [
                "code" => "205",
                "name" => "DiscoNight",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/205.png",
            ],
            [
                "code" => "79",
                "name" => "Chameleon",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/79.png",
            ],
            [
                "code" => "140",
                "name" => "FireChibi2",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/140.png",
            ],
            [
                "code" => "103",
                "name" => "JewelLuxury",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/103.png",
            ],
            [
                "code" => "109",
                "name" => "RaveJumpMobile",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/109.png",
            ],
            [
                "code" => "111",
                "name" => "FlyOut",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/111.png",
            ],
            [
                "code" => "117",
                "name" => "5Godbeasts",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/117.png",
            ],
            [
                "code" => "127",
                "name" => "GodofWarM",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/127.png",
            ],
            [
                "code" => "204",
                "name" => "LuckyBoxes",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/204.png",
            ],
            [
                "code" => "98",
                "name" => "AllStarTeam",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/98.png",
            ],
            [
                "code" => "118",
                "name" => "SkrSkr",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/118.png",
            ],
            [
                "code" => "123",
                "name" => "LuckyBatsM",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/123.png",
            ],
            [
                "code" => "129",
                "name" => "GuGuGu2M",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/129.png",
            ],
            [
                "code" => "130",
                "name" => "GoldStealer",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/130.png",
            ],
            [
                "code" => "138",
                "name" => "Move n' Jump",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/138.png",
            ],
            [
                "code" => "61",
                "name" => "Mr.Bean",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/61.png",
            ],
            [
                "code" => "64",
                "name" => "Zeus",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/64.png",
            ],
            [
                "code" => "67",
                "name" => "GoldenEggs",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/67.png",
            ],
            [
                "code" => "194",
                "name" => "Fortune Dragon",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/194.png",
            ],
            [
                "code" => "5007",
                "name" => "Da Fa Cai",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/5007.png",
            ],
            [
                "code" => "161",
                "name" => "Hercules",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/161.png",
            ],
            [
                "code" => "187",
                "name" => "Wing Chun",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/187.png",
            ],
            [
                "code" => "195",
                "name" => "Lord Ganesha",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/195.png",
            ],
            [
                "code" => "196",
                "name" => "Tenfold Eggs",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/196.png",
            ],
            [
                "code" => "5009",
                "name" => "Uproar in Heaven",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/5009.png",
            ],
            [
                "code" => "157",
                "name" => "5Boxing",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/157.png",
            ],
            [
                "code" => "153",
                "name" => "SixCandy",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/153.png",
            ],
            [
                "code" => "163",
                "name" => "NeZhaAdvent",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/163.png",
            ],
            [
                "code" => "179",
                "name" => "Jump High 2",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/179.png",
            ],
            [
                "code" => "183",
                "name" => "Wolf Disco",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/183.png",
            ],
            [
                "code" => "148",
                "name" => "FortuneTotem",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/148.png",
            ],
            [
                "code" => "160",
                "name" => "FaCaiShen2",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/160.png",
            ],
            [
                "code" => "171",
                "name" => "GreekGods",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/171.png",
            ],
            [
                "code" => "GO169",
                "name" => "Dragon Pachinko",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GO169.png",
            ],
            [
                "code" => "185",
                "name" => "Dragon Ball",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/185.png",
            ],
            [
                "code" => "186",
                "name" => "Fire Queen 2",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/186.png",
            ],
            [
                "code" => "AT101",
                "name" => "Supercars",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AT101.png",
            ],
            [
                "code" => "5008",
                "name" => "Da Hong Zhong",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/5008.png",
            ],
            [
                "code" => "146",
                "name" => "SkyLanterns",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/146.png",
            ],
            [
                "code" => "150",
                "name" => "Shou-Xin",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/150.png",
            ],
            [
                "code" => "152",
                "name" => "DoubleFly",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/152.png",
            ],
            [
                "code" => "154",
                "name" => "Kronos",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/154.png",
            ],
            [
                "code" => "173",
                "name" => "6Toros",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/173.png",
            ],
            [
                "code" => "182",
                "name" => "Thor 2",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/182.png",
            ],
            [
                "code" => "180",
                "name" => "Gu Gu Gu 3",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/180.png",
            ],
            [
                "code" => "184",
                "name" => "Six Gacha",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/184.png",
            ],
            [
                "code" => "147",
                "name" => "FlowerFortunes",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/147.png",
            ],
            [
                "code" => "188",
                "name" => "Cricket Fever",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/188.png",
            ],
            [
                "code" => "225",
                "name" => "Mr. Miser",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/225.png",
            ],
            [
                "code" => "214",
                "name" => "Ninja Raccoon",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/214.png",
            ],
            [
                "code" => "GB198",
                "name" => "HanumanBingo",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB198.png",
            ],
            [
                "code" => "215",
                "name" => "Hot Pinatas",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/215.png",
            ],
            [
                "code" => "229",
                "name" => "Night City",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/229.png",
            ],
            [
                "code" => "243",
                "name" => "Mafia",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/243.png",
            ],
            [
                "code" => "222",
                "name" => "Loy Krathong",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/222.png",
            ],
            [
                "code" => "GB11",
                "name" => "ThaiFishPrawnCrab",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB11.png",
            ],
            [
                "code" => "227",
                "name" => "888 Cai Shen",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/227.png",
            ],
            [
                "code" => "231",
                "name" => "Striker WILD",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/231.png",
            ],
            [
                "code" => "199",
                "name" => "Songkran Festival",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/199.png",
            ],
            [
                "code" => "GB2",
                "name" => "MonsterHunter",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB2.png",
            ],
            [
                "code" => "226",
                "name" => "Lucky Tigers",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/226.png",
            ],
            [
                "code" => "212",
                "name" => "Burning Xi-You",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/212.png",
            ],
            [
                "code" => "213",
                "name" => "Mini Roulette",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/213.png",
            ],
            [
                "code" => "241",
                "name" => "The Chicken House",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/241.png",
            ],
            [
                "code" => "197",
                "name" => "Dragon's Treasure",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/197.png",
            ],
            [
                "code" => "216",
                "name" => "Xoc Dia",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/216.png",
            ],
            [
                "code" => "223",
                "name" => "Acrobatics",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/223.png",
            ],
            [
                "code" => "210",
                "name" => "Oo Ga Cha Ka",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/210.png",
            ],
            [
                "code" => "224",
                "name" => "K.O. Island",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/224.png",
            ],
            [
                "code" => "GB12",
                "name" => "Myeong-ryang",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB12.png",
            ],
            [
                "code" => "217",
                "name" => "Mahjong Fruit",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/217.png",
            ],
            [
                "code" => "GB3",
                "name" => "CoinSpinner",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB3.png",
            ],
            [
                "code" => "GO01",
                "name" => "Dragon Ball Dozer",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GO01.png",
            ],
            [
                "code" => "GB10",
                "name" => "Seotda",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB10.png",
            ],
            [
                "code" => "GB14",
                "name" => "FunkyBingo",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB14.png",
            ],
            [
                "code" => "242",
                "name" => "Treasure Pirate",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/242.png",
            ],
            [
                "code" => "177",
                "name" => "Aladdin's lamp",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/177.png",
            ],
            [
                "code" => "218",
                "name" => "Dollar Bomb",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/218.png",
            ],
            [
                "code" => "220",
                "name" => "Floating Market",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/220.png",
            ],
            [
                "code" => "GB5",
                "name" => "HotDJ",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB5.png",
            ],
            [
                "code" => "206",
                "name" => "Sweet POP",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/206.png",
            ],
            [
                "code" => "208",
                "name" => "Money Tree",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/208.png",
            ],
            [
                "code" => "GB1",
                "name" => "321Go!",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB1.png",
            ],
            [
                "code" => "228",
                "name" => "Mirror Mirror",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/228.png",
            ],
            [
                "code" => "211",
                "name" => "King of Atlantis",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/211.png",
            ],
            [
                "code" => "GB6",
                "name" => "GaneshaJr.",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB6.png",
            ],
            [
                "code" => "219",
                "name" => "King Kong Shake",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/219.png",
            ],
            [
                "code" => "207",
                "name" => "Thai HILO",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/207.png",
            ],
            [
                "code" => "209",
                "name" => "The Cupids",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/209.png",
            ],
            [
                "code" => "GB9",
                "name" => "FootballFever",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB9.png",
            ],
            [
                "code" => "GB16",
                "name" => "CHICAGOⅡ",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB16.png",
            ],
            [
                "code" => "1200",
                "name" => "AliceRunJP",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/1200.png",
            ],
            [
                "code" => "GB8",
                "name" => "DragonKoi",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB8.png",
            ],
            [
                "code" => "200",
                "name" => "Alice Run",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/200.png",
            ],
            [
                "code" => "230",
                "name" => "Baseball Fever",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/230.png",
            ],
            [
                "code" => "GB13",
                "name" => "FootballFeverM",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB13.png",
            ],
            [
                "code" => "GB7",
                "name" => "Mummy's Treasure",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB7.png",
            ],
            [
                "code" => "GB15",
                "name" => "Heroofthe3Kingdoms-CaoCao",
                "game_type_id" => 1,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GB15.png",
            ],
            [
                "code" => "AT01",
                "name" => "Oneshot Fishing",
                "game_type_id" => 8,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AT01.png",
            ],
            [
                "code" => "AB3",
                "name" => "Paradise",
                "game_type_id" => 8,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AB3.png",
            ],
            [
                "code" => "AT05",
                "name" => "LuckyFishing",
                "game_type_id" => 8,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/AT05.png",
            ],
            [
                "code" => "GO02",
                "name" => "Hero Fishing",
                "game_type_id" => 8,
                "product_id" =>5,
                "image_url" => "http://swmd.6633663.com/Image/CQ9/en/GO02.png",
            ],
        ];

        GameList::insert($data);
    }
}
